//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberBoss.Domain.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBoss.Domain.Extensions.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount deve ser maior ou igual a zero..
        /// </summary>
        public static string AMOUNT_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("AMOUNT_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarberName é obrigatório e deve ter entre 2 e 80 caracteres..
        /// </summary>
        public static string BARBERNAME_IS_INVALID {
            get {
                return ResourceManager.GetString("BARBERNAME_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inválido para compra.
        /// </summary>
        public static string BILLING_STATUS_IS_INVALID {
            get {
                return ResourceManager.GetString("BILLING_STATUS_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturamento Cancelado deve ter o valor 0..
        /// </summary>
        public static string CANCELED_BILLING_MUST_BE_ZERO {
            get {
                return ResourceManager.GetString("CANCELED_BILLING_MUST_BE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientName é obrigatório e deve ter entre 2 e 120 caracteres..
        /// </summary>
        public static string CLIENTNAME_IS_INVALID {
            get {
                return ResourceManager.GetString("CLIENTNAME_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de uma compra não pode ser negativo.
        /// </summary>
        public static string PAID_BILLING_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("PAID_BILLING_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de pagamento é inválido.
        /// </summary>
        public static string PAYMENT_METHOD_IS_INVALID {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceName é obrigatório e deve ter entre 2 e 120 caracteres..
        /// </summary>
        public static string SERVICENAME_IS_INVALID {
            get {
                return ResourceManager.GetString("SERVICENAME_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes não pode exceder 500 caracteres..
        /// </summary>
        public static string TOO_MANY_NOTES {
            get {
                return ResourceManager.GetString("TOO_MANY_NOTES", resourceCulture);
            }
        }
    }
}
